require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProducersController do

  def mock_producer(stubs={})
    @mock_producer ||= mock_model(Producer, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all producers as @producers" do
      Producer.stub(:all) { [mock_producer] }
      get :index
      assigns(:producers).should eq([mock_producer])
    end
  end

  describe "GET show" do
    it "assigns the requested producer as @producer" do
      Producer.stub(:find).with("37") { mock_producer }
      get :show, :id => "37"
      assigns(:producer).should be(mock_producer)
    end
  end

  describe "GET new" do
    it "assigns a new producer as @producer" do
      Producer.stub(:new) { mock_producer }
      get :new
      assigns(:producer).should be(mock_producer)
    end
  end

  describe "GET edit" do
    it "assigns the requested producer as @producer" do
      Producer.stub(:find).with("37") { mock_producer }
      get :edit, :id => "37"
      assigns(:producer).should be(mock_producer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created producer as @producer" do
        Producer.stub(:new).with({'these' => 'params'}) { mock_producer(:save => true) }
        post :create, :producer => {'these' => 'params'}
        assigns(:producer).should be(mock_producer)
      end

      it "redirects to the created producer" do
        Producer.stub(:new) { mock_producer(:save => true) }
        post :create, :producer => {}
        response.should redirect_to(producer_url(mock_producer))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved producer as @producer" do
        Producer.stub(:new).with({'these' => 'params'}) { mock_producer(:save => false) }
        post :create, :producer => {'these' => 'params'}
        assigns(:producer).should be(mock_producer)
      end

      it "re-renders the 'new' template" do
        Producer.stub(:new) { mock_producer(:save => false) }
        post :create, :producer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested producer" do
        Producer.stub(:find).with("37") { mock_producer }
        mock_producer.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :producer => {'these' => 'params'}
      end

      it "assigns the requested producer as @producer" do
        Producer.stub(:find) { mock_producer(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:producer).should be(mock_producer)
      end

      it "redirects to the producer" do
        Producer.stub(:find) { mock_producer(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(producer_url(mock_producer))
      end
    end

    describe "with invalid params" do
      it "assigns the producer as @producer" do
        Producer.stub(:find) { mock_producer(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:producer).should be(mock_producer)
      end

      it "re-renders the 'edit' template" do
        Producer.stub(:find) { mock_producer(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested producer" do
      Producer.stub(:find).with("37") { mock_producer }
      mock_producer.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the producers list" do
      Producer.stub(:find) { mock_producer }
      delete :destroy, :id => "1"
      response.should redirect_to(producers_url)
    end
  end

end
